<!DOCTYPE html>
<html lang="en" itemscope itemtype="https://schema.org/WebPage">
<head>
  <!-- Basic Page Needs
================================================== -->
  <meta charset="utf-8">
  <title itemprop="name">EMI Certificate, EMI Registration - Sunconsultants</title>

  <!-- Mobile Specific Metas
================================================== -->
  <meta name="robots" content="index, follow">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name=author content="Sun Consultants &amp; Engineers">
  <meta name=generator content="">
  <link rel="canonical" href="https://sunconsultants.co.in/emi-certification-consultants" />
    <meta name="description" itemprop="description" content="Electromagnetic Interference, EMI Testing, EMI EMC Standards, EMI Certificate, EMI Registration, EMI Consultant"/>


  <!-- Favicon
================================================== -->
<link rel="icon" type="image/png" href="assets/img/favicon.png">
  <!-- CSS
================================================== -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <!-- FontAwesome -->
  <link rel="stylesheet" href="plugins/fontawesome/css/all.min.css">
  <!-- Animation -->
  <link rel="stylesheet" href="plugins/animate-css/animate.css">
  <!-- slick Carousel -->
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <link rel="stylesheet" href="plugins/slick/slick-theme.css">
  <!-- Colorbox -->
  <link rel="stylesheet" href="plugins/colorbox/colorbox.css">
  <!-- Template styles-->
  <link rel="stylesheet" href="css/style.css">
      <!-- Google tag (gtag.js) Google Analytics tracking-->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163953232-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-163953232-1');
</script>

</head>
<body>
  <div class="body-inner">
    <!--/ Topbar end -->
<!-- Header start -->

<div class="include-file">
        <?php include('include/nenu.php'); ?>
      </div>
<!--/ Header end -->
<section id="main-container" class="main-container">
        <div class="container">
             <div class="col-md-12">
                       <ul class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
        <li class="wow fadeInUp" itemprop="itemListElement" itemscope  itemtype="https://schema.org/ListItem"><a itemprop="item" itemprop="name" href="/">
        <span itemprop="name">Home</span>
        </a><meta itemprop="position" content="1" /></li>
        <li style="" class="wow fadeInUp" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">/ 
            <span itemprop="name">EMI Registration Certification</span><meta itemprop="position" content="2" /></li>
    </ul>
                         <h3 class="text-center p-4">EMI / EMC</h3>
                </div>
       
      <div class="row">
          <div class="col-lg-6">
            <h1 class="column-title">EMI Registration Certification</h1>
           <p><b>EMI</b>/EMC<b> testing</b> is a critical step in bringing a new product to market. ... Emissions testing - measures the amount of electromagnetic noise generated by a device during normal operation. The purpose of these tests is to ensure that any emission from the device are below the relevant limits defined for that type of device.</p>
           
          </div><!-- Col end -->
  
          <div class="col-lg-6 mt-5 mt-lg-0">
            
            <div id="page-slider" class="page-slider small-bg">
  
                <div class="item" style="background-image:url(img/img-update/emi-1.webp)">
                  <div class="container">
                      <div class="box-slider-content">
                        
                      </div>
                  </div>
                </div><!-- Item 1 end -->
  
                <div class="item" style="background-image:url(img/img-update/emi-2.webp)">
                  <div class="container">
                      <div class="box-slider-content">
                       
                      </div>
                  </div>
                </div><!-- Item 1 end -->
  
                <div class="item" style="background-image:url(img/img-update/emi-6.webp)">
                  <div class="container">
                      <div class="box-slider-content">
                           
                        </div>    
                      </div>
                  </div>
                  <div class="item" style="background-image:url(img/img-update/emi-4.webp)">
                    <div class="container">
                        <div class="box-slider-content">
                             
                          </div>    
                        </div>
                    </div>
                    <div class="item" style="background-image:url(img/img-update/emi-5.webp)">
                        <div class="container">
                            <div class="box-slider-content">
                                 
                              </div>    
                            </div>
                            
                        </div>
                        
                </div><!-- Item 1 end -->
                
            </div><!-- Page slider end-->          
          
            <div class="call-to-action-btn">
                <a class="btn btn-primary " href="#">
                    EMI / EMC TESTING MORE DETAILS.</a>
              </div>
          </div><!-- Col end -->
      </div><!-- Content row end -->
  
    </div><!-- Container end -->
  </section><!-- Main container end -->
<!---body------->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-lg-6"></div>
    <div class="col-sm-6 col-lg-6"></div>
  </div>
</div>
<!--/ News end -->
<!-------------footer id start on this  ------------------>
<div class="footer">
      <?php include('include/footer.php'); ?>
    </div>
    <!-- whatapps -->

    <div class="whatsapps">
      <?php include('include/whatsapps.php'); ?>
    </div>
    <!-- popup -->



  <!-- Javascript Files
  ================================================== -->

  <!-- initialize jQuery Library -->
  <script src="plugins/jQuery/jquery.min.js"></script>
  <!-- Bootstrap jQuery -->
  <script src="plugins/bootstrap/bootstrap.min.js" defer></script>
  <!-- Slick Carousel -->
  <script src="plugins/slick/slick.min.js"></script>
  <script src="plugins/slick/slick-animation.min.js"></script>
  <!-- Color box -->
  <!--<script src="plugins/colorbox/jquery.colorbox.js"></script>-->
  <!-- shuffle -->
  <!--<script src="plugins/shuffle/shuffle.min.js" defer></script>-->


  <!-- Google Map API Key-->
  <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" defer></script>-->
  
  <!-- Google Map Plugin-->
  <!--<script src="plugins/google-map/map.js" defer></script>-->

  <!-- Template custom -->
  <script src="js/script.js"></script>

  </div><!-- Body inner end -->
  </body>

  </html>